// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:12d2414e-fe76-4290-971f-b74d88ca7491",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SLENZPc4l",
    "aws_user_pools_web_client_id": "7hssbs6t6k743kcfh9cp8b0vlh",
    "oauth": {}
};


export default awsmobile;
